version: '3.8'
services:
  web:
    container_name: web
    build: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DEBUG=${DEBUG}
    volumes:
      - ./bitmind:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
      container_name: db
      image: postgres:13-alpine
      environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      volumes:
        - postgres_data:/var/lib/postgresql/data/


volumes:
  postgres_data: